language: php
php: 8.0
services:
  - docker

notifications:
  email:
    - team@appwrite.io

before_script:
  - composer install --ignore-platform-reqs

script:
  - docker-compose up -d
  - docker-compose exec tests vendor/bin/pint --test
  - docker-compose exec tests vendor/bin/phpstan analyse
  - docker-compose exec tests vendor/bin/phpunit