version: '3.1'

services:

  tests:
    container_name: utopia-mongo-test-1
    build:
      context: .
    networks:
      - database
    volumes:
      - ./:/usr/src/code
    ports:
      - "8708:8708"

  mongo:
    image: mongo:4.4
    container_name: utopia-mongo-1
    networks:
      - database
    ports:
      - "8703:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  database:
