version: '3.1'

services:

  tests:
    container_name: tests
    build:
      context: .
    networks:
      - database
    volumes:
      - ./:/usr/src/code
    ports:
      - "8708:8708"

  adminer:
    image: adminer
    container_name: utopia-adminer
    restart: always
    ports:
      - "8760:8080"
    networks:
      - database

  postgres:
    image: postgres:13
    container_name: utopia-postgres
    networks:
      - database
    ports:
      - "8700:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  cockroach:
    image: cockroachdb/cockroach:v20.2.0
    container_name: utopia-cockroach
    command: start-single-node --insecure --logtostderr
    networks:
      - database
    ports:
      - "8704:26257"
      - "8705:8080"

  mariadb:
    image: mariadb:10.5
    container_name: utopia-mariadb
    networks:
      - database
    ports:
      - "8701:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
  
  mongo:
    image: mongo:4.4
    container_name: utopia-mongo
    networks:
      - database
    ports:
      - "8702:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mysql:
    image: mysql:8.0.28-oracle
    container_name: utopia-mysql
    networks:
      - database
    ports:
      - "8703:3307"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: default
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3307
    cap_add:
      - SYS_NICE

  redis:
    image: redis:6.0-alpine
    container_name: utopia-redis
    networks:
      - database

networks:
  database:
