name: "Tests"

on: [ pull_request ]
jobs:
  lint:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.3'] # add PHP versions as required

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: git checkout HEAD^2

      - name: Compose install
        run: |
          docker run --rm -v $PWD:/app composer sh -c \
          "composer install --profile --ignore-platform-reqs"

      - name: Build
        run: |
          export PHP_VERSION=${{ matrix.php-versions }}
          docker compose build
          docker compose up -d
          sleep 10

      - name: Run Tests
        run: docker compose exec tests vendor/bin/phpunit